swipe:
  3:
    right:
      command: 'xdotool key XF86Back'
    left:
      command: 'xdotool key XF86Forward'
    up:
      command:  'qdbus org.kde.kglobalaccel /component/kwin invokeShortcut "ExposeAll"'
      threshold: 1
    down:
      command: 'qdbus org.kde.kglobalaccel /component/kwin invokeShortcut "ExposeAll"'
  4:
    left:
      command: 'xdotool --clearmodifiers key alt+Tab'
    right:
      command: 'xdotool --clearmodifiers key super+Right'
    up:
      command: 'qdbus org.kde.kglobalaccel /component/kwin invokeShortcut "ExposeAll"'
    down:
      command: 'qdbus org.kde.kglobalaccel /component/kwin invokeShortcut "ExposeAll"'
pinch:
  2:
    in:
      command: 'xdotool --clearmodifiers key ctrl+plus'
      threshold: 0.1
    out:
      command: 'xdotool --clearmodifiers key ctrl+minus'
      threshold: 0.1

threshold:
  swipe: 1
  pinch: 1

interval:
  swipe: 1
  pinch: 1
