swipe:
  3:
    right:
      command: 'xdotool key XF86Back'
    left:
      command: 'xdotool key XF86Forward'
    up:
      command:  'qdbus org.kde.kglobalaccel /component/kwin invokeShortcut "ExposeAll"'
      threshold: 1
    down:
      command: 'xdotool getactivewindow windowminimize'
  4:
    left:
      command: 'xdotool key alt+Tab'
    right:
      command: 'xdotool key super+Right'
    up:
      command: 'qdbus org.kde.kglobalaccel /component/kwin invokeShortcut "ExposeAll"'
    down:
      command: 'wmctrl -c :ACTIVE:'
pinch:
  2:
    in:
      command: 'xdotool key ctrl+plus'
      threshold: 0.1
    out:
      command: 'xdotool key ctrl+minus'
      threshold: 0.1

threshold:
  swipe: .6
  pinch: 1

interval:
  swipe: 1
  pinch: 1
